[package]
name = "rs-zombies"
version = "0.2.0"
authors = ["autodidaddict <alothien@gmail.com>"]

[dependencies]
protobuf        = "1.4.*"
futures         = "0.*"
futures-cpupool = "0.1.*"
tls-api         = "0.1.*"
grpc = "0.2.1"

[build-dependencies]
protoc-rust-grpc = "0.2.1"