[package]
name = "rs-zombies"
version = "0.1.0"
authors = ["autodidaddict <alothien@gmail.com>"]

[dependencies]
protobuf        = "1.*"
futures         = "0.*"
futures-cpupool = "0.1.*"
tls-api         = "0.*"
grpc = "0.1.11"

[build-dependencies]
protoc-rust-grpc = "0.1.11"